### ISSUE TITLE
lambda runtime

### ISSUE THREAD

**Issue by liwen-tj** [disel-espol/olscheduler#7]
How do you execute lambda?  
How do you lanunch your lambda runtime?
I cannot find any docker or container opearation code.

**Comment by cristina-abad** [comment]
This is an extension to OpenLambda (a research project from the University of Wisconsin). The instructions on how to launch functions on OpenLambda are available on their repo: https://github.com/open-lambda/open-lambda

**Comment by liwen-tj** [comment]
I alse read source code of OpenLambda.   I find there is only one worker(process) in OpenLambda. You cannot new a worker.  But in your ol-scheduler, you have many workers in config.json. I donot understand how you combined your code with Openlambda.

By the way,  I also read your paper <Beyond Load Balancing: Package-Aware Scheduling for Serverless Platforms> PASch.  I don't find PASch branch in <https://github.com/open-lambda/open-lambda>. Will you please give me the complete source code of PASch. I really want to read it! Many thanks！
